pipeline:
  name: build
  identifier: build
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: sarang071
        build: <+input>
  stages:
    - stage:
        name: Pre-checks
        identifier: Prechecks
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushECR
                  name: BuildAndPushECR_1
                  identifier: BuildAndPushECR_1
                  spec:
                    connectorRef: AWS
                    region: ap-south-1
                    account: "058264202818"
                    imageName: 058264202818.dkr.ecr.ap-south-1.amazonaws.com/nginx
                    tags:
                      - Test
                    dockerfile: ./Dockerfile
        when:
          pipelineStatus: Success
          condition: "## This is a comment"
        delegateSelectors:
          - docker-delegate
        strategy:
          parallelism: 1
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: Abort
